source = ~/.config/hypr/colors-hyprlock.conf

# splash = false # Uncomment to disable the quote at the bottom of the screen

wallpaper {
    monitor = 
    path = $wallpaper
    # ipc = on
    # timeout = 900
}